export default function TermsOfService() {
  return (
    <div className="legal-page">
      <h1>Terms of Service</h1>
      <p className="updated">Last updated: {new Date().toLocaleDateString()}</p>

      <section>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using AboutMyFace AI (the "App"), you accept and agree to be bound by
          these Terms of Service ("Terms"). If you do not agree to these Terms, you may not use the
          App. We reserve the right to modify these Terms at any time, and your continued use of the
          App constitutes acceptance of any changes.
        </p>
      </section>

      <section>
        <h2>2. Entertainment Purpose Only</h2>
        <p>
          This App is for entertainment purposes only. Face readings, personality insights, and
          fortune predictions are not scientific and should not be used for:
        </p>
        <ul>
          <li>Medical diagnosis or health decisions</li>
          <li>Employment or hiring decisions</li>
          <li>Legal matters or court proceedings</li>
          <li>Professional advice of any kind</li>
          <li>Making important life decisions</li>
          <li>Psychological or clinical assessment</li>
        </ul>
        <p>
          The App provides readings for fun and entertainment only. You acknowledge that the results
          are generated by AI and are not based on verified scientific methods.
        </p>
      </section>

      <section>
        <h2>3. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Use the App lawfully and in accordance with these Terms</li>
          <li>Not upload inappropriate, offensive, or illegal content</li>
          <li>Not attempt to reverse engineer, decompile, or hack the service</li>
          <li>Keep your account credentials secure and confidential</li>
          <li>Not use the App to harass, abuse, or harm others</li>
          <li>Only upload photos you have the right to use</li>
          <li>Not use the App for any commercial purpose without permission</li>
          <li>Comply with all applicable laws and regulations</li>
        </ul>
      </section>

      <section>
        <h2>4. Account Registration</h2>
        <p>
          To use certain features of the App, you must register for an account. You are responsible
          for maintaining the confidentiality of your account credentials and for all activities that
          occur under your account. You agree to notify us immediately of any unauthorized use of
          your account.
        </p>
      </section>

      <section>
        <h2>5. Subscriptions and Payments</h2>
        <p>
          The App offers in-app purchases and subscriptions through Apple's App Store. All payments
          are processed by Apple, and you agree to their terms and conditions. Subscriptions
          automatically renew unless canceled at least 24 hours before the end of the current period.
          You can manage your subscription in your App Store account settings. Refunds are subject to
          Apple's refund policy.
        </p>
      </section>

      <section>
        <h2>6. Intellectual Property</h2>
        <p>
          All content, features, functionality, design, code, and technology of the App are owned by
          AboutMyFace AI and are protected by international copyright, trademark, patent, trade
          secret, and other intellectual property laws. You may not copy, modify, distribute, sell,
          or lease any part of our services without our explicit written permission.
        </p>
      </section>

      <section>
        <h2>7. User Content</h2>
        <p>
          By uploading photos to the App, you grant us a worldwide, non-exclusive, royalty-free
          license to use, process, and analyze the photos solely for the purpose of providing the
          face reading service. We do not claim ownership of your photos. You represent that you have
          all necessary rights to upload and use any photos you submit.
        </p>
      </section>

      <section>
        <h2>8. Disclaimer of Warranties</h2>
        <p>
          THE APP IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER
          EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR
          A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. We do not warrant that the App will be
          uninterrupted, secure, or error-free. We make no guarantees about the accuracy,
          reliability, or completeness of any face readings or analysis results.
        </p>
      </section>

      <section>
        <h2>9. Limitation of Liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ABOUTMYFACE AI SHALL NOT BE LIABLE FOR ANY
          INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS
          OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL,
          OR OTHER INTANGIBLE LOSSES RESULTING FROM:
        </p>
        <ul>
          <li>Your use or inability to use the App</li>
          <li>Any decisions made based on face reading results</li>
          <li>Unauthorized access to or alteration of your data</li>
          <li>Any bugs, viruses, or malicious code in the App</li>
          <li>Any errors or omissions in any content</li>
        </ul>
      </section>

      <section>
        <h2>10. Indemnification</h2>
        <p>
          You agree to indemnify, defend, and hold harmless AboutMyFace AI and its officers,
          directors, employees, and agents from any claims, liabilities, damages, losses, and
          expenses arising out of your use of the App, violation of these Terms, or infringement of
          any third-party rights.
        </p>
      </section>

      <section>
        <h2>11. Termination</h2>
        <p>
          We reserve the right to terminate or suspend your account and access to the App at our sole
          discretion, without notice, for conduct that we believe violates these Terms or is harmful
          to other users, us, or third parties. Upon termination, your right to use the App will
          immediately cease.
        </p>
      </section>

      <section>
        <h2>12. Changes to Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. When we make material changes, we
          will update the "Last updated" date at the top of this page and, if required, provide
          additional notice. Your continued use of the App after changes constitutes acceptance of
          the updated Terms.
        </p>
      </section>

      <section>
        <h2>13. Governing Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of the
          State of New Jersey, United States, without regard to its conflict of law
          provisions. Any disputes arising from these Terms or your use of the App shall be resolved
          in the courts of New Jersey.
        </p>
      </section>

      <section>
        <h2>14. Contact</h2>
        <p>Questions about these Terms? Contact us at:</p>
        <p>
          GOOD VIBES FACTORY, LLC
          <br />
          Email: support@aboutmyface.ai
          <br />
          Website: www.aboutmyface.ai
        </p>
      </section>

      <section>
        <p style={{ fontSize: '0.9rem', lineHeight: '1.6', fontStyle: 'italic' }}>
          By using AboutMyFace AI, you acknowledge that you have read, understood, and agree to be
          bound by these Terms of Service. This is an entertainment app and should not be used for
          professional, medical, or legal purposes.
        </p>
      </section>
    </div>
  );
}
